apiVersion: v1
kind: ConfigMap
metadata:
  name: productapisettings
  namespace: {{.Values.namespace}}
data:
  DataAccessClientSettings__ProductContainerName: "{{ .Values.container }}"
  DataAccessClientSettings__DatabaseName: "{{ .Values.db }}"
  DataAccessClientSettings__ConnectionString: "{{ .Values.connectionString }}"