apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
 name: productserver
 namespace: amcart
spec:
 hosts:
   - '*'
 gateways:
   - istio-ingress/root-gateway
 http:
 - match:
   - uri:
       prefix: /api/v1/products
   route:
   - destination:
       host: product-api-svc.amcart.svc.cluster.local
       port:
         number: 8080