apiVersion: v1
kind: Service
metadata:
  name: product-api-svc
  namespace: {{.Values.namespace}}
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: product-api
