name: Deploy on AKS
on:
  push:
    branches:
      - "feature"
jobs:
  build:
    name: "Deploy on AKS"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASS }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.ACR_USERNAME}}/${{secrets.repo}}:productAPiv1
          context: ./ProductWebApi
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}

      - uses: azure/k8s-bake@v1
        with:
          renderEngine: "helm2"
          helmChart: "./k8s/product-chart"
          helm-version: "latest"
          overrides: |
            imagePath:${{ secrets.ACR_USERNAME}}/${{secrets.repo}}:productAPiv1
            container:${{secrets.container}}
            db:${{secrets.db}}
            connectionString:${{secrets.connectionString}}
            namespace:${{secrets.namespace}}
        id: bake
      - uses: azure/k8s-deploy@v1
        with:
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          namespace: ${{secrets.namespace}}
          images: |
            ${{ secrets.ACR_USERNAME}}/${{secrets.repo}}:productAPiv1
